name: ruff-fix
on:
  push:
    paths:
      - '**/*.py'
  pull_request:
    paths:
      - '**/*.py'

permissions:
  contents: write   # → 자동 Push 권한

jobs:
  ruff_autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install --upgrade ruff
      - run: ruff check --fix .
      - name: Commit & push back
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: auto-fix imports via ruff"
